### ISSUE TITLE
ZdcIOBuffer does not always flush correctly

### ISSUE THREAD

**Issue by hellerve** [svenvc/zodiac#13]
As per [this Discord comment](https://discord.com/channels/223421264751099906/278558427796602882/1139144051665408071), pushing a large enough contiguous block of Unicode characters into a buffer will make it overflow and never flush it (it’s only flushed conditionally in `ZdcIOBuffer>>#next:putAll:startingAt:`, and the condition never matches).

Here’s a simple example of the behavior:

```
(ZnEntity text: ('å' repeat: 2049))
    writeOn: (ZnBivalentWriteStream
            on: (ZdcSecureSocketStream openConnectionToHostNamed: 'google.com' port: 443)
                    connect)
```

This only works with `ZnStringEntity` because it uses a `ZnCharacterEncoder` internally, and the one for `UTF8`, for instance, chops the string into blocks through Unicode. Thus, this could also be fixed in Zinc instead, but it seems that the buffer itself should probably have a check instead (either flush at the start or the of `ZdcIOBuffer>>#next:putAll:startingAt:` if it’s full), since it likely has multiple dependents that might potentially use it in a currently broken way.

Cheers

**Comment by svenvc** [comment]
Hi,

This is a good catch ! How did you figure this out ? This edge case has been present for years I think.

I tried the following fix: https://github.com/svenvc/zodiac/commit/ad0458cde7e536f59e9fe4ca41afdfee0c39bf95

It passed all tests, but now my image is broken, so I need to make sure this was not the cause.

Sven

**Comment by svenvc** [comment]
OK, my image crash does not seem to be related to this change, I tried in another image.

**Comment by hellerve** [comment]
Hey!

Great, this is equivalent to the fix I was using locally to test whether it would resolve the issue.

We were sending big JSON payloads with a lot of Unicode in a server application, and the stars aligned on one of the requests, I suppose :)

**Comment by svenvc** [comment]
OK, thanks for the feedback and the excellent reporting.
