### ISSUE TITLE
Zodiac: ZdcAbstractSocketStream and ZdcAbstractSSLSession as abstract classes 

### ISSUE THREAD

**Issue by astares** [svenvc/zodiac#9]
Issue: https://github.com/pharo-project/pharo/issues/8734 with 
PR: https://github.com/pharo-project/pharo/pull/8735

**Comment by svenvc** [comment]
Done: https://github.com/svenvc/zodiac/commit/89b2035993f97c41599f0afe88b7564b62cefa0e
